'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { readSync, encodePng } = require('image-js');

const cursorsFolder = path.join(
  __dirname,
  '../openchemlib/src/main/resources/images/cursor',
);
const cursorNames = fs.readdirSync(cursorsFolder);

const cursors = cursorNames.map((cursorName) => {
  const cursorImage = readSync(path.join(cursorsFolder, cursorName));
  const smallerCursor = cursorImage.resize({ width: 24, height: 24 });
  const png = encodePng(smallerCursor);
  const base64Url = Buffer.from(png).toString('base64');
  return { name: cursorName, base64Url };
});

let js = `'use strict';

// This file is generated by scripts/create_24px_cursors.js
// Do not modify it manually

const cursors = {
`;

for (const { name, base64Url } of cursors) {
  js += `  '${name}': 'url(data:image/png;base64,${base64Url})',\n`;
}

js += `};

module.exports = cursors;
`;

fs.writeFileSync(
  path.join(__dirname, '../lib/canvas_editor/cursors_24px.js'),
  js,
);
