import fs from 'node:fs';
import path from 'node:path';

import { encodePng, readSync } from 'image-js';

const cursorsFolder = path.join(
  import.meta.dirname,
  '../openchemlib/src/main/resources/images/cursor',
);
const cursorNames = fs.readdirSync(cursorsFolder);

const cursors = cursorNames.map((cursorName) => {
  const cursorImage = readSync(path.join(cursorsFolder, cursorName));
  const smallerCursor = cursorImage.resize({ width: 24, height: 24 });
  const png = encodePng(smallerCursor);
  const base64Url = Buffer.from(png).toString('base64');
  return { name: cursorName, base64Url };
});

let js = `// This file is generated by scripts/create_24px_cursors.js
// Do not modify it manually

export const cursors = {
`;

for (const { name, base64Url } of cursors) {
  js += `  '${name}': 'url(data:image/png;base64,${base64Url})',\n`;
}

js += `};
`;

fs.writeFileSync(
  path.join(import.meta.dirname, '../lib/canvas_editor/cursors_24px.js'),
  js,
);
