name: TypeDoc

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  typedoc:
    # Documentation: https://github.com/zakodium/workflows#typedoc
    uses: zakodium/workflows/.github/workflows/typedoc.yml@typedoc-v1
    with:
      entry: 'lib/index.d.ts'
      name: OpenChemLib JS
    secrets:
      github-token: ${{ secrets.BOT_TOKEN }}
